In [1]:
from datasets import load_dataset
import pandas as pd 

ds=load_dataset("electricsheepafrica/nigerian_realestate_commercial_properties",split="train")

df=pd.DataFrame(ds)


df.head()

c:\Users\PBuva\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,property_id,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,listing_date
0,COMM-0708125,Kano,office,340,6984431,occupied,2,2024-05-03
1,COMM-0919426,Benin City,warehouse,3523,52630271,occupied,5,2023-04-16
2,COMM-0649047,Kano,warehouse,723,5580530,occupied,5,2022-11-22
3,COMM-0271738,Port Harcourt,showroom,193,4764099,vacant,2,2023-10-17
4,COMM-0438423,Enugu,office,278,13060740,occupied,2,2022-02-27

In [6]:
type(df['property_id'].tolist()[0])

str

In [7]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

df['occupancy_status']=encoder.fit_transform(df['occupancy_status'])   # occupied =0 , vacant=1
df

,property_id,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,listing_date
0,COMM-0708125,Kano,office,340,6984431,0,2,2024-05-03
1,COMM-0919426,Benin City,warehouse,3523,52630271,0,5,2023-04-16
2,COMM-0649047,Kano,warehouse,723,5580530,0,5,2022-11-22
3,COMM-0271738,Port Harcourt,showroom,193,4764099,1,2,2023-10-17
4,COMM-0438423,Enugu,office,278,13060740,0,2,2022-02-27
...,...,...,...,...,...,...,...,...
99995,COMM-0960813,Lagos,warehouse,2876,22018909,0,5,2024-05-14
99996,COMM-0113535,Ibadan,retail_shop,273,9059038,1,5,2025-01-07
99997,COMM-0429947,Abuja,showroom,197,9305034,0,3,2024-09-28
99998,COMM-0857007,Kano,office,384,17894426,0,2,2023-09-19
99999,COMM-0222342,Lagos,showroom,169,6809863,1,1,2024-01-07

In [8]:
from sklearn.preprocessing import LabelEncoder

df['commercial_type'].value_counts()

encoder1=LabelEncoder()
df['commercial_type']=encoder1.fit_transform(df['commercial_type'])

df

,property_id,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,listing_date
0,COMM-0708125,Kano,0,340,6984431,0,2,2024-05-03
1,COMM-0919426,Benin City,3,3523,52630271,0,5,2023-04-16
2,COMM-0649047,Kano,3,723,5580530,0,5,2022-11-22
3,COMM-0271738,Port Harcourt,2,193,4764099,1,2,2023-10-17
4,COMM-0438423,Enugu,0,278,13060740,0,2,2022-02-27
...,...,...,...,...,...,...,...,...
99995,COMM-0960813,Lagos,3,2876,22018909,0,5,2024-05-14
99996,COMM-0113535,Ibadan,1,273,9059038,1,5,2025-01-07
99997,COMM-0429947,Abuja,2,197,9305034,0,3,2024-09-28
99998,COMM-0857007,Kano,0,384,17894426,0,2,2023-09-19
99999,COMM-0222342,Lagos,2,169,6809863,1,1,2024-01-07

In [10]:
df['city'].unique()

array(['Kano', 'Benin City', 'Port Harcourt', 'Enugu', 'Lagos', 'Ibadan',
       'Owerri', 'Abuja', 'Uyo', 'Calabar'], dtype=object)

In [9]:
encoder1.classes_

array(['office', 'retail_shop', 'showroom', 'warehouse'], dtype=object)

In [11]:
# feature engineering 
import numpy as np

df['rent_sqm']=(df['annual_rent']/df['size_sqm'])
df['lease_term_short']=np.where(df['lease_term_years']<2,1,0)
df['log_size_sqm']=np.log(df['size_sqm'])

In [12]:
df.columns

Index(['property_id', 'city', 'commercial_type', 'size_sqm', 'annual_rent',
       'occupancy_status', 'lease_term_years', 'listing_date', 'rent_sqm',
       'lease_term_short', 'log_size_sqm'],
      dtype='object')

In [13]:
df=df[['property_id', 'listing_date', 'city', 'commercial_type', 'size_sqm', 'annual_rent',
       'occupancy_status', 'lease_term_years', 'rent_sqm',
       'lease_term_short', 'log_size_sqm']]
df.head()

,property_id,listing_date,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,rent_sqm,lease_term_short,log_size_sqm
0,COMM-0708125,2024-05-03,Kano,0,340,6984431,0,2,20542.444118,0,5.828946
1,COMM-0919426,2023-04-16,Benin City,3,3523,52630271,0,5,14939.049390,0,8.167068
2,COMM-0649047,2022-11-22,Kano,3,723,5580530,0,5,7718.575380,0,6.583409
3,COMM-0271738,2023-10-17,Port Harcourt,2,193,4764099,1,2,24684.450777,0,5.262690
4,COMM-0438423,2022-02-27,Enugu,0,278,13060740,0,2,46981.079137,0,5.627621

In [14]:
# engineering scoring features

df['city_median_rent_sqm']=df.groupby('city')['size_sqm'].transform('median')   # helps measure mispricing 
df['city_listing_count']=df.groupby('city')['property_id'].transform('count')   # buyer density / competition

C:\Users\PBuva\AppData\Local\Temp\ipykernel_21480\131214608.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city_median_rent_sqm']=df.groupby('city')['size_sqm'].transform('median')   # helps measure mispricing
C:\Users\PBuva\AppData\Local\Temp\ipykernel_21480\131214608.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city_listing_count']=df.groupby('city')['property_id'].transform('count')   # buyer density / competition

In [17]:
df.groupby('city')['property_id'].count()

city
Abuja            19951
Benin City        3987
Calabar           3989
Enugu             4906
Ibadan            7036
Kano              6006
Lagos            40258
Owerri            1948
Port Harcourt     9888
Uyo               2031
Name: property_id, dtype: int64

In [15]:
df.groupby('city')['size_sqm'].median()

city
Abuja            242.0
Benin City       238.0
Calabar          243.0
Enugu            238.0
Ibadan           244.0
Kano             241.0
Lagos            241.0
Owerri           241.0
Port Harcourt    240.5
Uyo              238.0
Name: size_sqm, dtype: float64

In [24]:
df.head()

,property_id,listing_date,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,rent_sqm,lease_term_short,log_size_sqm,city_median_rent_sqm,city_listing_count
0,COMM-0708125,2024-05-03,Kano,0,340,6984431,0,2,20542.444118,0,5.828946,241.0,6006
1,COMM-0919426,2023-04-16,Benin City,3,3523,52630271,0,5,14939.049390,0,8.167068,238.0,3987
2,COMM-0649047,2022-11-22,Kano,3,723,5580530,0,5,7718.575380,0,6.583409,241.0,6006
3,COMM-0271738,2023-10-17,Port Harcourt,2,193,4764099,1,2,24684.450777,0,5.262690,240.5,9888
4,COMM-0438423,2022-02-27,Enugu,0,278,13060740,0,2,46981.079137,0,5.627621,238.0,4906

In [25]:
# mispricing score
df['mispricing_score']=abs(df['rent_sqm']-df['city_median_rent_sqm'])/df['city_median_rent_sqm']
df['mispricing_score']

C:\Users\PBuva\AppData\Local\Temp\ipykernel_30572\3147806935.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mispricing_score']=abs(df['rent_sqm']-df['city_median_rent_sqm'])/df['city_median_rent_sqm']

0         84.238357
1         61.769115
2         31.027284
3        101.638049
4        196.399492
            ...
99995     30.768000
99996    134.997088
99997    194.180476
99998    192.361277
99999    166.199367
Name: mispricing_score, Length: 100000, dtype: float64

In [26]:
# df=df.drop(columns=['liquidity_score'])
# df

df['liquidity_score']=((1-(df['log_size_sqm']/df['log_size_sqm'].max())) + df['lease_term_short']+df['occupancy_status'])/3
df.head()

C:\Users\PBuva\AppData\Local\Temp\ipykernel_30572\695110666.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['liquidity_score']=((1-(df['log_size_sqm']/df['log_size_sqm'].max())) + df['lease_term_short']+df['occupancy_status'])/3

,property_id,listing_date,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,rent_sqm,lease_term_short,log_size_sqm,city_median_rent_sqm,city_listing_count,mispricing_score,liquidity_score
0,COMM-0708125,2024-05-03,Kano,0,340,6984431,0,2,20542.444118,0,5.828946,241.0,6006,84.238357,0.105203
1,COMM-0919426,2023-04-16,Benin City,3,3523,52630271,0,5,14939.049390,0,8.167068,238.0,3987,61.769115,0.013695
2,COMM-0649047,2022-11-22,Kano,3,723,5580530,0,5,7718.575380,0,6.583409,241.0,6006,31.027284,0.075676
3,COMM-0271738,2023-10-17,Port Harcourt,2,193,4764099,1,2,24684.450777,0,5.262690,240.5,9888,101.638049,0.460698
4,COMM-0438423,2022-02-27,Enugu,0,278,13060740,0,2,46981.079137,0,5.627621,238.0,4906,196.399492,0.113083

In [27]:
df['velocity_score']=0.5*(df['liquidity_score']) + 0.5*(1/df['mispricing_score'])   # high score --> high velocity
df['ranking_score']=0.4*(df['velocity_score'])+0.3*(df['liquidity_score'])+0.3*(df['mispricing_score'])   # final score for ranking 
df=df.sort_values(by='ranking_score',ascending=False)
df.head(10)

C:\Users\PBuva\AppData\Local\Temp\ipykernel_30572\73286006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['velocity_score']=0.5*(df['liquidity_score']) + 0.5*(1/df['mispricing_score'])   # high score --> high velocity
C:\Users\PBuva\AppData\Local\Temp\ipykernel_30572\73286006.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ranking_score']=0.4*(df['velocity_score'])+0.3*(df['liquidity_score'])+0.3*(df['mispricing_score'])   # final score for ranking

,property_id,listing_date,city,commercial_type,size_sqm,annual_rent,occupancy_status,lease_term_years,rent_sqm,lease_term_short,log_size_sqm,city_median_rent_sqm,city_listing_count,mispricing_score,liquidity_score,velocity_score,ranking_score
16309,COMM-0983484,2022-08-02,Enugu,1,261,15644199,1,1,59939.459770,1,5.564520,238.0,4906,250.846470,0.782219,0.393103,75.645848
35803,COMM-0367286,2023-11-02,Uyo,2,139,8329420,1,1,59923.884892,1,4.934474,238.0,2031,250.781029,0.806877,0.405432,75.638545
648,COMM-0162417,2023-04-17,Benin City,2,88,5279227,0,1,59991.215909,1,4.477337,238.0,3987,251.063932,0.491435,0.247709,75.565694
1904,COMM-0669851,2023-06-14,Benin City,2,101,6055362,1,2,59954.079208,0,4.615121,238.0,3987,250.907896,0.486043,0.245014,75.516187
12066,COMM-0506876,2022-02-13,Enugu,1,41,2457098,0,1,59929.219512,1,3.713572,238.0,4906,250.803443,0.521327,0.262657,75.502494
62057,COMM-0282405,2022-06-05,Enugu,2,242,14506552,0,1,59944.429752,1,5.488938,238.0,4906,250.867352,0.451844,0.227915,75.486925
53387,COMM-0016821,2024-03-26,Uyo,2,192,11508467,0,1,59939.932292,1,5.257495,238.0,2031,250.848455,0.460902,0.232444,75.485785
75797,COMM-0314727,2023-11-28,Uyo,2,296,17742829,1,3,59941.989865,0,5.690359,238.0,2031,250.857100,0.443961,0.223973,75.479908
74808,COMM-0671609,2022-12-28,Enugu,2,264,15815352,1,3,59906.636364,0,5.575949,238.0,4906,250.708556,0.448438,0.226213,75.437584
63576,COMM-0113097,2024-12-23,Enugu,2,251,15031815,1,2,59887.709163,0,5.525453,238.0,4906,250.629030,0.450415,0.227202,75.414714

In [28]:
df.columns

Index(['property_id', 'listing_date', 'city', 'commercial_type', 'size_sqm',
       'annual_rent', 'occupancy_status', 'lease_term_years', 'rent_sqm',
       'lease_term_short', 'log_size_sqm', 'city_median_rent_sqm',
       'city_listing_count', 'mispricing_score', 'liquidity_score',
       'velocity_score', 'ranking_score'],
      dtype='object')

In [ ]:
import xgboost as xgb  
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score


cols=['rent_sqm','log_size_sqm','city_median_rent_sqm','city_listing_count','lease_term_short']   # don't use occupany status here ... (overfit)
X=df[cols]
Y=df['velocity_score']

velocity_model=XGBRegressor()
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=123)
velocity_model.fit(X_train,Y_train)

Y_pred=velocity_model.predict(X_test)

print(r2_score(Y_test,Y_pred))

0.5332049938466362

In [40]:
import xgboost as xgb  
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

cols=['rent_sqm','log_size_sqm','lease_term_short','city_listing_count']
X=df[cols]
Y=df['liquidity_score']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=123)

liquidity_model=XGBRegressor()
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=123)
liquidity_model.fit(X_train,Y_train)

Y_pred=liquidity_model.predict(X_test)

r2_score(Y_test,Y_pred)

0.5383754149379631

In [46]:
import xgboost as xgb 
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

cols=['log_size_sqm','lease_term_short','city_listing_count','city_median_rent_sqm','commercial_type']
X=df[cols]
Y=df['ranking_score']

ranking_model=XGBRegressor()

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=123)

ranking_model.fit(X_train,Y_train)

Y_pred=ranking_model.predict(X_test)

r2_score(Y_test,Y_pred)

0.608865433087901

In [61]:
import pandas as pd 

df['rank']=range(1,len(df)+1)


# neutral ranking for both buyers and sellers.

df['priority']=pd.qcut(       # 0 to 5% - immediate , 5 to 20% - High priority , 20% to 50%-Watchlist,50%-100% - Low priority
    df['rank'],
    q=[0,0.05,0.2,0.5,1.0],
    labels=['Immediate Action','High Priority','Watchlist','Low Priority']
)

df_front=df[['property_id', 'listing_date', 'city', 'commercial_type', 'size_sqm',
       'annual_rent', 'occupancy_status', 'lease_term_years', 'rent_sqm', 
        'priority']]


df_front['occupancy_status'].replace({1:'Vacant',0:'Occupied'},inplace=True)
df_front['commercial_type'].replace({0:'office',1:'retail_shop',2:'showroom',3:'warehouse'})


properties_json=df_front.to_dict(orient='records')

properties_json[:10]

C:\Users\PBuva\AppData\Local\Temp\ipykernel_30572\2400153522.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_front['occupancy_status'].replace({1:'Vacant',0:'Occupied'},inplace=True)
C:\Users\PBuva\AppData\Local\Temp\ipykernel_30572\2400153522.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_front['occupancy_status'].replace({1:'Vacant',0:'Occupied'},inplace=True)

[{'property_id': 'COMM-0983484',
  'listing_date': '2022-08-02',
  'city': 'Enugu',
  'commercial_type': 1,
  'size_sqm': 261,
  'annual_rent': 15644199,
  'occupancy_status': 'Vacant',
  'lease_term_years': 1,
  'rent_sqm': 59939.45977011494,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0367286',
  'listing_date': '2023-11-02',
  'city': 'Uyo',
  'commercial_type': 2,
  'size_sqm': 139,
  'annual_rent': 8329420,
  'occupancy_status': 'Vacant',
  'lease_term_years': 1,
  'rent_sqm': 59923.88489208633,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0162417',
  'listing_date': '2023-04-17',
  'city': 'Benin City',
  'commercial_type': 2,
  'size_sqm': 88,
  'annual_rent': 5279227,
  'occupancy_status': 'Occupied',
  'lease_term_years': 1,
  'rent_sqm': 59991.21590909091,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0669851',
  'listing_date': '2023-06-14',
  'city': 'Benin City',
  'commercial_type': 2,
  'size_sqm': 101,
  'annual_rent': 6055362,
  'occupancy_status': 'Vacant',
  'lease_term_years': 2,
  'rent_sqm': 59954.07920792079,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0506876',
  'listing_date': '2022-02-13',
  'city': 'Enugu',
  'commercial_type': 1,
  'size_sqm': 41,
  'annual_rent': 2457098,
  'occupancy_status': 'Occupied',
  'lease_term_years': 1,
  'rent_sqm': 59929.21951219512,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0282405',
  'listing_date': '2022-06-05',
  'city': 'Enugu',
  'commercial_type': 2,
  'size_sqm': 242,
  'annual_rent': 14506552,
  'occupancy_status': 'Occupied',
  'lease_term_years': 1,
  'rent_sqm': 59944.42975206611,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0016821',
  'listing_date': '2024-03-26',
  'city': 'Uyo',
  'commercial_type': 2,
  'size_sqm': 192,
  'annual_rent': 11508467,
  'occupancy_status': 'Occupied',
  'lease_term_years': 1,
  'rent_sqm': 59939.932291666664,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0314727',
  'listing_date': '2023-11-28',
  'city': 'Uyo',
  'commercial_type': 2,
  'size_sqm': 296,
  'annual_rent': 17742829,
  'occupancy_status': 'Vacant',
  'lease_term_years': 3,
  'rent_sqm': 59941.98986486487,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0671609',
  'listing_date': '2022-12-28',
  'city': 'Enugu',
  'commercial_type': 2,
  'size_sqm': 264,
  'annual_rent': 15815352,
  'occupancy_status': 'Vacant',
  'lease_term_years': 3,
  'rent_sqm': 59906.63636363636,
  'priority': 'Immediate Action'},
 {'property_id': 'COMM-0113097',
  'listing_date': '2024-12-23',
  'city': 'Enugu',
  'commercial_type': 2,
  'size_sqm': 251,
  'annual_rent': 15031815,
  'occupancy_status': 'Vacant',
  'lease_term_years': 2,
  'rent_sqm': 59887.70916334661,
  'priority': 'Immediate Action'}]

In [68]:
import json

file=open("properties.json","w")
json.dump(properties_json,file)
file.close()

In [62]:
import pickle 
velocity_pickle=open('velocity_model.pkl',"wb")
liquidity_pickle=open('liquidity_model.pkl',"wb")
ranking_pickle=open('ranking_model.pkl',"wb")
pickle.dump(velocity_model,velocity_pickle)
pickle.dump(liquidity_model,liquidity_pickle)
pickle.dump(ranking_model,ranking_pickle)
velocity_pickle.close()
liquidity_pickle.close()
ranking_pickle.close()

In [ ]:
import pickle

city_file=open("city_median_map.pkl","wb")
city_median_map = {
    "Abuja": 242.0,
    "Benin City": 238.0,
    "Calabar": 243.0,
    "Enugu": 238.0,
    "Ibadan": 244.0,
    "Kano": 241.0,
    "Lagos": 241.0,
    "Owerri": 241.0,
    "Port Harcourt": 240.5,
    "Uyo": 238.0
}

pickle.dump(city_median_map,city_file)

In [18]:
import pickle

city_count_file=open("city_listing_count.pkl","wb")
city_count_map = {
    "Abuja": 19951,
    "Benin City": 3987,
    "Calabar": 3989,
    "Enugu": 4906,
    "Ibadan": 7036,
    "Kano": 6006,
    "Lagos": 40258,
    "Owerri": 1948,
    "Port Harcourt": 9888,
    "Uyo": 2031
}

pickle.dump(city_count_map,city_count_file)